server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    driverClassName: ${MYSQL_DRIVER}

jwt:
  secret: ${JWT_SECRET}