CREATE TABLE lesson (
   id INT AUTO_INCREMENT NOT NULL,
   name VARCHAR(256) NOT NULL,
   update_at DATETIME NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE homework (
   id INT AUTO_INCREMENT NOT NULL,
   name VARCHAR(256) NOT NULL,
   description VARCHAR(256) NOT NULL,
   lesson_id INT NOT NULL,
   PRIMARY KEY (id),
   CONSTRAINT fk_lesson FOREIGN KEY (lesson_id) REFERENCES lesson(id) ON DELETE CASCADE
);