CREATE TABLE homework (
   id INT AUTO_INCREMENT NOT NULL,
   name VARCHAR(256) NOT NULL,
   description VARCHAR(256) NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE lesson (
   id INT AUTO_INCREMENT NOT NULL,
   name VARCHAR(256) NOT NULL,
   homework_id INT NOT NULL,
   PRIMARY KEY(id),
   CONSTRAINT PRIMARY KEY homework_id REFERENCES homework(id)
   ON DELETE CASCADE
);